# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190819_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='title',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='profile_pic',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
