# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentmail', '0002_auto_20190816_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads'),
        ),
    ]
