# Generated by Django 2.2.4 on 2019-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentmail', '0003_auto_20190819_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
