# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-15 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=1200)),
                ('sender_port', models.IntegerField(max_length=6)),
                ('email_host_user', models.CharField(max_length=1200)),
                ('email_host_password', models.CharField(max_length=1200)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_use_tls', models.BooleanField(default=True)),
            ],
        ),
    ]
