# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='sender_port',
            field=models.IntegerField(),
        ),
    ]
